name: Frontend Application Deploy

on:
  push:
    branches:
      - master
    paths:
    - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash

    - name: install
      working-directory: ./client
      run: |
        yarn install

    - name: build
      working-directory: ./client
      run: |
        yarn build

    - name: upload application build result
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./client/build


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: download application build result
      uses: actions/download-artifact@v1
      with:
        name: build
        path: ./client/build

    # sync assets
    - uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --cache-control 'max-age=31536000' --exclude '*.html' --exclude '*.js.map' --exclude '*.js.LICENSE'
      env:
        SOURCE_DIR: './client/build'
        AWS_REGION: 'ap-northeast-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # sync index.html
    - uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --cache-control 'max-age=30' --include '*.html' --exclude '*'
      env:
        SOURCE_DIR: './client/build'
        AWS_REGION: 'ap-northeast-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
